// Enregistre un past paper corrigé dans le Google Drive de l'élève :
// Google Doc propre (énoncés + notation + corrigés) rangé dans
// « Coach Emma Student / <Subject> / », nommé par date et score.
import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/routeAuth";
import { getAccessToken, ensureFolder, uploadHtmlAsDoc, driveConfigured } from "@/lib/googleDrive";
import { getSubject } from "@/lib/subjects";
import type { Exercise, ExerciseMark } from "@/lib/types";

export const maxDuration = 60;

function esc(s: string) {
  return String(s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export async function POST(req: NextRequest) {
  const auth = await requireUser();
  if (!auth) return NextResponse.json({ error: "not signed in" }, { status: 401 });
  if (!driveConfigured()) return NextResponse.json({ error: "Google Drive is not configured yet" }, { status: 503 });

  const body = await req.json().catch(() => ({}));
  const attemptId = String(body?.attempt_id || "");
  if (!attemptId) return NextResponse.json({ error: "missing attempt" }, { status: 400 });

  const { data: attempt } = await auth.sb
    .from("attempts")
    .select("id, lesson_id, payload, result, created_at")
    .eq("id", attemptId)
    .eq("user_id", auth.user.id)
    .eq("kind", "exercise")
    .maybeSingle();
  if (!attempt) return NextResponse.json({ error: "paper not found" }, { status: 404 });

  const { data: lesson } = await auth.sb
    .from("lessons")
    .select("title, subject, exam_board, spec_topic")
    .eq("id", attempt.lesson_id)
    .maybeSingle();

  const token = await getAccessToken(auth.sb, auth.user.id);
  if (!token) return NextResponse.json({ error: "not_connected" }, { status: 428 });

  const exercises = ((attempt.payload as { exercises?: Exercise[] })?.exercises || []) as Exercise[];
  const mark = attempt.result as (ExerciseMark & { drive_link?: string }) | null;
  const awarded = mark ? mark.items.reduce((s, i) => s + (i.marks_awarded || 0), 0) : null;
  const total = mark
    ? mark.items.reduce((s, i) => s + (i.marks_total || 0), 0)
    : exercises.reduce((s, e) => s + (e.marks || 0), 0);

  const subjLabel = getSubject(lesson?.subject || "maths").labelEn;
  const date = new Date(attempt.created_at as string).toISOString().slice(0, 10);
  const name = `${date} — ${lesson?.title || "Practice paper"}${awarded !== null ? ` — ${awarded}/${total} marks` : ""}`;

  // Le document : en-tête façon paper + questions + (si corrigé) la notation.
  const html = `
<h1>${esc(lesson?.title || "Practice paper")}</h1>
<p><b>${esc(subjLabel)}</b> · ${esc(lesson?.exam_board || "A Level")} · ${esc(lesson?.spec_topic || "")} · ${date} · ${total} marks${awarded !== null ? ` · <b>scored ${awarded}/${total}</b>` : ""}</p>
<hr/>
${exercises
  .map((e, i) => {
    const it = mark?.items.find((x) => x.id === e.id);
    return `
<h2>Question ${i + 1} ${e.command_word ? `— “${esc(e.command_word)}”` : ""} [${e.marks} marks]</h2>
<p>${esc(e.statement)}</p>
${it ? `
<p><b>Marks:</b> ${it.marks_awarded}/${it.marks_total} · ${esc(it.verdict)}</p>
<p><b>Feedback:</b> ${esc(it.feedback)}</p>
<p><b>Method marks:</b> ${esc(it.method_comment)}</p>
${it.misconception ? `<p><b>Misconception:</b> ${esc(it.misconception)}</p>` : ""}
<p><b>Model solution:</b></p><p>${esc(it.model_solution)}</p>` : "<p><i>Not marked yet.</i></p>"}
<hr/>`;
  })
  .join("\n")}
<p><i>Generated by Coach Emma Student.</i></p>`;

  try {
    const rootId = await ensureFolder(token, "Coach Emma Student");
    const subjectFolderId = await ensureFolder(token, subjLabel, rootId);
    const doc = await uploadHtmlAsDoc(token, { name, parentId: subjectFolderId, html });

    // On garde le lien dans la tentative (sans écraser la correction).
    await auth.sb
      .from("attempts")
      .update({ result: { ...(mark || {}), drive_link: doc.link, drive_file_id: doc.id } })
      .eq("id", attempt.id);

    return NextResponse.json({ link: doc.link });
  } catch (e) {
    return NextResponse.json({ error: (e as Error).message || "Drive save failed" }, { status: 502 });
  }
}
